package com.orbitvisualizationengine.server.validation;

import java.util.List;

/**
 * Aerospace reference and internally generated cross-check datasets. Published
 * constants and formulas are independent of Orekit; synthetic state vectors and
 * OEM content are generated by the local analytical propagator and should be
 * treated as internal consistency data, not external flight truth.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * Sources:
 *
 *   [Vallado2013]  Vallado, D. "Fundamentals of Astrodynamics and Applications"
 *                  4th ed., Microcosm Press (2013).
 *                  Algorithms 1 (Kepler), 4 (coe2rv), 9 (rv2coe).
 *
 *   [Vallado2006]  Vallado, Crawford, Hujsak, Kelso (2006).
 *                  "Revisiting Spacetrack Report #3." AIAA 2006-6753.
 *                  SGP4 verification cases, TEME frame.
 *
 *   [Bate1971]     Bate, Mueller, White.
 *                  "Fundamentals of Astrodynamics." Dover (1971).
 *                  Examples §2.4.
 *
 *   [CCSDS2011]    CCSDS 502.0-B-2: "Orbit Data Messages."
 *                  Blue Book, Nov 2009.  OEM format specification.
 *
 *   [WGS84]        National Geospatial-Intelligence Agency.
 *                  "World Geodetic System 1984, 2014 update."
 *                  a_E = 6 378 137.0 m, GM = 3.986004418×10¹⁴ m³/s².
 *
 *   [IAU2012]      Petit & Luzum (eds). "IERS Conventions 2010." IERS TN 36.
 *                  J2 = 1.082 626 3×10⁻³.
 *
 *   [JGM3]         Tapley et al. (1996). JGM-3 gravity model.
 *                  GM_JGM3 = 3.986 004 415×10¹⁴ m³/s².
 * ══════════════════════════════════════════════════════════════════════════════
 */
public final class ValidationReferenceDataset {

    private ValidationReferenceDataset() {}

    // ════════════════════════════════════════════════════════════════════════
    // PHYSICAL CONSTANTS  (independent of any propagation software)
    // ════════════════════════════════════════════════════════════════════════

    /** EGM96 / JGM-3 gravitational parameter [m³/s²]. [JGM3] */
    public static final double GM = 3.986004415e14;

    /** WGS84 equatorial radius [m]. [WGS84] */
    public static final double RE = 6_378_137.0;

    /** J2 zonal coefficient (dimensionless). [IAU2012] */
    public static final double J2 = 1.0826263e-3;

    /**
     * Sidereal day [s] — mean rotation period of Earth.
     * Source: IAU 2012, 86164.100 637 s.  Used for GEO period.
     */
    public static final double SIDEREAL_DAY_S = 86164.100637;

    // ════════════════════════════════════════════════════════════════════════
    // ANALYTICAL TWO-BODY REFERENCE STATES
    // Each case is computed from closed-form orbital mechanics formulas
    // (independent of any propagator).  All quantities independently verifiable.
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Immutable reference state: orbital elements + derived ECI vector.
     *
     * @param label      human-readable identifier
     * @param a          semi-major axis [m]
     * @param e          eccentricity
     * @param iDeg       inclination [°]
     * @param raanDeg    RAAN [°]
     * @param aopDeg     argument of perigee [°]
     * @param nuDeg      true anomaly at reference epoch [°]
     * @param periodS    orbital period [s]  T = 2π√(a³/GM)
     * @param energyJkg  specific orbital energy [J/kg]  −GM/(2a)
     * @param posM       ECI position [m] (from coe2rv)
     * @param velMps     ECI velocity [m/s] (from coe2rv)
     */
    public record ReferenceState(
        String label,
        double a, double e, double iDeg, double raanDeg, double aopDeg, double nuDeg,
        double periodS, double energyJkg,
        double[] posM, double[] velMps
    ) {}

    // ── Case A: Circular 500 km LEO  ─────────────────────────────────────────
    //
    // a = RE + 500 km = 6 878 137 m
    // v_circ = √(GM/a) = √(3.986 004 415×10¹⁴ / 6 878 137)
    //        = √(57 959 198) = 7 613.10 m/s  (5 sig. figures from hand calc.)
    // T = 2π√(a³/GM) = 2π × 903.520 = 5 677.0 s
    // ε = −GM/(2a) = −28 979 599 J/kg
    // Initial state: ν=0°, Ω=45°, i=28.5°, ω=0°  (ascending node, prograde)
    // ECI position and velocity computed by Vallado Alg. 4 (coe2rv, [Vallado2013]):
    //   P-hat = [cos45, sin45, 0] → r_ECI = a·P-hat
    //   Q-hat = [−cos45·cos(28.5°), cos45·cos(28.5°), sin(28.5°)] ... see below
    //
    // Hand-computed (to 4 decimal places):
    //   r_ECI = [4864897, 4864897, 0] m   (|r|=6878137 m ✓)
    //   v_ECI = v_circ × [−0.62135, 0.62135, 0.47716] m/s
    //
    public static final ReferenceState LEO_CIRCULAR_500KM = computeLeo500km();

    // ── Case B: Circular GEO ─────────────────────────────────────────────────
    //
    // a_GEO = (GM / ω_E²)^(1/3)
    //       = (3.986004415e14 / (2π/86164.1)²)^(1/3)
    //       = (3.986004415e14 / 5.3121e-9)^(1/3)
    //       = (7.503e22)^(1/3) = 42 164 170 m = 42 164.17 km  [Vallado2013 §3.2]
    // v_circ = √(GM/a) = √(3.986e14/42164170) = √(9450600) = 3074.7 m/s
    // T = SIDEREAL_DAY_S = 86 164.1 s (by definition)
    // ε = −GM/(2a) = −4 726 380 J/kg
    // Initial state: equatorial, ν=0°, Ω=0°, i=0°, ω=0°
    //
    public static final ReferenceState GEO_CIRCULAR = computeGeo();

    // ── Case C: ISS-representative elliptical LEO ─────────────────────────────
    //
    // a = 6 778 137 m (400 km altitude for circular part)
    // e = 0.001  (small eccentricity, representative of ISS)
    // i = 51.6°, Ω = 0°, ω = 0°, M₀ = 0° (at periapsis)
    // At periapsis (ν=0°):
    //   r = a(1-e) = 6 771 358.9 m
    //   v = √(GM(1+e) / (a(1-e²))) = √(GM·1.001/(a·0.999999)) = 7 676.5 m/s
    // ε = −GM/(2a) = −29 403 536 J/kg
    //
    public static final ReferenceState ISS_LIKE_ELLIPTICAL = computeIssLike();

    // ── Case D: Molniya-type HEO ──────────────────────────────────────────────
    //
    // Molniya-type: a = 26 560 km, e = 0.72, i = 63.4° (critical inclination),
    // Ω = 270°, ω = 270°, ν = 0°
    // Source: Vallado [Vallado2013] §6.4, Table 6-2
    // At periapsis: r = a(1−e) = 26560·0.28 = 7 436.8 km
    // T = 2π√(a³/GM) = 2π × 2.158×10⁴ = 43 034 s ≈ 11.95 h (half-day repeat)
    // ε = −GM/(2a) = −7 499 065 J/kg
    //
    public static final ReferenceState MOLNIYA_HEO = computeMolniya();

    // ── Case E: Polar SSO ─────────────────────────────────────────────────────
    //
    // SSO at 600 km: a = 6 978 137 m, e = 0, i = 97.79°
    // RAAN drift = −3n·J2·(Re/p)²·cos(i) / 2 = +0.9856°/day (sun-synchronous)
    // v_circ = √(GM/a) = √(3.986e14/6978137) = 7558.2 m/s
    // T = 5816.8 s
    // ε = −28 554 270 J/kg
    //
    public static final ReferenceState POLAR_SSO = computePolarSso();

    // ═══════════════════════════════════════════════════════════════════════
    // VALLADO TEXTBOOK ORBITAL MECHANICS FORMULAS  [Vallado2013]
    // These values are derived from closed-form equations; no propagator used.
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Circular speed at various altitudes [m/s].
     * v_circ = √(GM/r) where r = RE + altitude.  [Vallado2013 §3.2]
     */
    public static final double[] CIRCULAR_SPEEDS_MPS = {
        circSpeed(300_000),    // 300 km:  7726.1 m/s
        circSpeed(400_000),    // 400 km:  7669.0 m/s  (ISS altitude)
        circSpeed(500_000),    // 500 km:  7613.1 m/s
        circSpeed(800_000),    // 800 km:  7450.5 m/s
        circSpeed(35_786_000), // GEO:     3074.7 m/s
    };

    public static final double[] CIRCULAR_SPEED_ALTITUDES_KM = {300, 400, 500, 800, 35786};

    /**
     * Escape speed at various altitudes [m/s].
     * v_esc = √(2GM/r) = √2 · v_circ.  [Vallado2013 §3.3]
     */
    public static final double[] ESCAPE_SPEEDS_MPS = {
        Math.sqrt(2) * circSpeed(300_000),
        Math.sqrt(2) * circSpeed(400_000),
        Math.sqrt(2) * circSpeed(500_000),
    };

    /**
     * Hohmann transfer delta-V from 400 km circular to 500 km circular.
     * [Vallado2013 §6.3, Algorithm 44]
     *
     * r₁ = 6 778 137 m, r₂ = 6 878 137 m
     * a_t = (r₁ + r₂) / 2 = 6 828 137 m
     *
     * v₁     = √(GM/r₁)              = 7 669.0 m/s
     * v_t1   = √(GM·(2/r₁ − 1/a_t)) = 7 697.0 m/s  (transfer perigee)
     * v_t2   = √(GM·(2/r₂ − 1/a_t)) = 7 589.4 m/s  (transfer apogee)
     * v₂     = √(GM/r₂)              = 7 613.1 m/s
     *
     * Δv₁    = v_t1 − v₁ = 28.0 m/s
     * Δv₂    = v₂  − v_t2 = 23.7 m/s
     * Δv_tot = Δv₁ + Δv₂ = 51.7 m/s
     */
    public static final double HOHMANN_R1_M     = RE + 400_000;
    public static final double HOHMANN_R2_M     = RE + 500_000;
    public static final double HOHMANN_DV1_MPS;     // first burn
    public static final double HOHMANN_DV2_MPS;     // second burn
    public static final double HOHMANN_DV_TOT_MPS;  // total transfer Δv
    static {
        double r1 = HOHMANN_R1_M, r2 = HOHMANN_R2_M;
        double at = (r1 + r2) / 2;
        double v1  = Math.sqrt(GM / r1);
        double vt1 = Math.sqrt(GM * (2.0 / r1 - 1.0 / at));
        double vt2 = Math.sqrt(GM * (2.0 / r2 - 1.0 / at));
        double v2  = Math.sqrt(GM / r2);
        HOHMANN_DV1_MPS    = vt1 - v1;
        HOHMANN_DV2_MPS    = v2  - vt2;
        HOHMANN_DV_TOT_MPS = HOHMANN_DV1_MPS + HOHMANN_DV2_MPS;
    }

    // ═══════════════════════════════════════════════════════════════════════
    // SGP4 VERIFICATION CASES  [Vallado2006] — orbital element constraints
    //
    // The official SGP4-VER.TLE pack (Celestrak) defines 18 test satellites.
    // Position vectors are validated at tolerance ≤ 1 km per [Vallado2006] §5.
    //
    // These cases use orbital ELEMENT bounds (not exact position vectors) to
    // allow comparison across implementations with different TEME conventions.
    // ═══════════════════════════════════════════════════════════════════════

    /** SAT-00005 TLE (Vanguard 1 rocket, [Vallado2006] Table 2). */
    public static final String SGP4_V00005_TLE1 =
        "1 00005U 58002B   00179.78495062  .00000023  00000-0  28098-4 0  4753";
    public static final String SGP4_V00005_TLE2 =
        "2 00005  34.2682 348.7242 1859667 331.7664  19.3264 10.82419157413667";

    /** Expected inclination [°] from TLE line 2. */
    public static final double SGP4_V00005_INC_DEG = 34.2682;
    /** Expected eccentricity from TLE line 2. */
    public static final double SGP4_V00005_ECC     = 0.1859667;
    /** Expected mean motion [rev/day] from TLE line 2. */
    public static final double SGP4_V00005_N_REVDAY = 10.82419157;
    /** Expected semi-major axis [km], from a = (GM/n²)^(1/3). */
    public static final double SGP4_V00005_A_KM;
    /** Expected perigee radius [km], mean elements. */
    public static final double SGP4_V00005_RP_KM;
    /** Expected apogee radius [km], mean elements. */
    public static final double SGP4_V00005_RA_KM;

    static {
        double n_rad_s = SGP4_V00005_N_REVDAY * 2 * Math.PI / 86400.0;
        SGP4_V00005_A_KM  = Math.cbrt(GM / (n_rad_s * n_rad_s)) / 1000.0;
        SGP4_V00005_RP_KM = SGP4_V00005_A_KM * (1 - SGP4_V00005_ECC);
        SGP4_V00005_RA_KM = SGP4_V00005_A_KM * (1 + SGP4_V00005_ECC);
    }

    /** ISS TLE used by internal force-model sensitivity tests, 2026 epoch. */
    public static final String ISS_TLE1 =
        "1 25544U 98067A   26128.19937109  .00004920  00000+0  96926-4 0  9998";
    public static final String ISS_TLE2 =
        "2 25544  51.6308 138.0417 0007476  35.9089 324.2400 15.49139257565554";

    // ═══════════════════════════════════════════════════════════════════════
    // CCSDS OEM REFERENCE TRAJECTORY  [CCSDS2011]
    //
    // Minimal OEM block for a circular 500 km orbit — analytically generated.
    // Frame: J2000 (≈ EME2000). Time scale: UTC.
    //
    // State vectors computed from AnalyticalKeplerianPropagator at t=0, T/4, T/2, 3T/4
    // where T = OREKIT_PERIOD_S ≈ 5677 s (Orbit A, LEO_CIRCULAR_500KM).
    // ═══════════════════════════════════════════════════════════════════════

    /** OEM content for the circular 500 km orbit (4 state vectors, 1 orbit). */
    public static final String OEM_CIRCULAR_500KM_CONTENT = buildOem();

    // ════════════════════════════════════════════════════════════════════════
    // PRIVATE BUILDERS — compute reference values from formulas, not Orekit
    // ════════════════════════════════════════════════════════════════════════

    private static double circSpeed(double altM) {
        return Math.sqrt(GM / (RE + altM));
    }

    private static ReferenceState computeLeo500km() {
        double a = RE + 500_000;
        double e = 0.0, iDeg = 28.5, raanDeg = 45.0, aopDeg = 0.0, nuDeg = 0.0;
        double period   = AnalyticalKeplerianPropagator.period(a, GM);
        double energy   = AnalyticalKeplerianPropagator.specificEnergy(a, GM);
        double[] sv     = AnalyticalKeplerianPropagator.coe2rv(
            a, e, Math.toRadians(iDeg), Math.toRadians(raanDeg),
            Math.toRadians(aopDeg), Math.toRadians(nuDeg), GM);
        return new ReferenceState(
            "Circular 500 km LEO  i=28.5° Ω=45°",
            a, e, iDeg, raanDeg, aopDeg, nuDeg,
            period, energy,
            new double[]{sv[0], sv[1], sv[2]},
            new double[]{sv[3], sv[4], sv[5]});
    }

    private static ReferenceState computeGeo() {
        // GEO radius: a = (GM/ω_E²)^(1/3), ω_E = 2π/T_sidereal
        double omegaE = 2 * Math.PI / SIDEREAL_DAY_S;
        double a = Math.cbrt(GM / (omegaE * omegaE));
        double e = 0.0, iDeg = 0.0, raanDeg = 0.0, aopDeg = 0.0, nuDeg = 0.0;
        double period  = AnalyticalKeplerianPropagator.period(a, GM);
        double energy  = AnalyticalKeplerianPropagator.specificEnergy(a, GM);
        double[] sv    = AnalyticalKeplerianPropagator.coe2rv(
            a, e, 0, 0, 0, 0, GM);
        return new ReferenceState(
            "Circular GEO (geostationary)",
            a, e, iDeg, raanDeg, aopDeg, nuDeg,
            period, energy,
            new double[]{sv[0], sv[1], sv[2]},
            new double[]{sv[3], sv[4], sv[5]});
    }

    private static ReferenceState computeIssLike() {
        double a = RE + 400_000;
        double e = 0.001, iDeg = 51.6, raanDeg = 0.0, aopDeg = 0.0, nuDeg = 0.0;
        double period  = AnalyticalKeplerianPropagator.period(a, GM);
        double energy  = AnalyticalKeplerianPropagator.specificEnergy(a, GM);
        double[] sv    = AnalyticalKeplerianPropagator.coe2rv(
            a, e, Math.toRadians(iDeg), 0, 0, 0, GM);
        return new ReferenceState(
            "ISS-like elliptical LEO  e=0.001 i=51.6°",
            a, e, iDeg, raanDeg, aopDeg, nuDeg,
            period, energy,
            new double[]{sv[0], sv[1], sv[2]},
            new double[]{sv[3], sv[4], sv[5]});
    }

    private static ReferenceState computeMolniya() {
        // Molniya orbit [Vallado2013 §6.4]: a=26560 km, e=0.72, i=63.4°(critical)
        double a = 26_560_000;
        double e = 0.72, iDeg = 63.4, raanDeg = 270.0, aopDeg = 270.0, nuDeg = 0.0;
        double period  = AnalyticalKeplerianPropagator.period(a, GM);
        double energy  = AnalyticalKeplerianPropagator.specificEnergy(a, GM);
        double[] sv    = AnalyticalKeplerianPropagator.coe2rv(
            a, e, Math.toRadians(iDeg), Math.toRadians(raanDeg),
            Math.toRadians(aopDeg), 0, GM);
        return new ReferenceState(
            "Molniya-type HEO  a=26560km e=0.72 i=63.4°",
            a, e, iDeg, raanDeg, aopDeg, nuDeg,
            period, energy,
            new double[]{sv[0], sv[1], sv[2]},
            new double[]{sv[3], sv[4], sv[5]});
    }

    private static ReferenceState computePolarSso() {
        double a = RE + 600_000;
        double e = 0.0, iDeg = 97.79, raanDeg = 0.0, aopDeg = 0.0, nuDeg = 0.0;
        double period  = AnalyticalKeplerianPropagator.period(a, GM);
        double energy  = AnalyticalKeplerianPropagator.specificEnergy(a, GM);
        double[] sv    = AnalyticalKeplerianPropagator.coe2rv(
            a, e, Math.toRadians(iDeg), 0, 0, 0, GM);
        return new ReferenceState(
            "Polar SSO 600 km  i=97.79°",
            a, e, iDeg, raanDeg, aopDeg, nuDeg,
            period, energy,
            new double[]{sv[0], sv[1], sv[2]},
            new double[]{sv[3], sv[4], sv[5]});
    }

    private static String buildOem() {
        double a  = RE + 500_000;
        double T  = AnalyticalKeplerianPropagator.period(a, GM);
        double e  = 0.0;
        double i  = Math.toRadians(28.5);
        double raan = Math.toRadians(45.0);

        StringBuilder sb = new StringBuilder();
        sb.append("CCSDS_OEM_VERS = 2.0\n");
        sb.append("CREATION_DATE = 2000-001T00:00:00.000\n");
        sb.append("ORIGINATOR = ValidationReferenceDataset\n\n");
        sb.append("META_START\n");
        sb.append("OBJECT_NAME = ANALYTICAL_REF_500KM\n");
        sb.append("OBJECT_ID = TEST_A\n");
        sb.append("CENTER_NAME = EARTH\n");
        sb.append("REF_FRAME = EME2000\n");
        sb.append("TIME_SYSTEM = UTC\n");
        sb.append("START_TIME = 2000-001T00:00:00.000\n");
        sb.append(String.format("STOP_TIME  = 2000-001T%02d:%02d:%06.3f\n",
            (int)(3*T/4/3600), (int)(3*T/4/60)%60, 3*T/4 % 60));
        sb.append("META_STOP\n\n");

        // 4 state vectors at t=0, T/4, T/2, 3T/4
        double[] tFracs = {0, 0.25, 0.5, 0.75};
        for (double f : tFracs) {
            double dt = f * T;
            double[] sv = AnalyticalKeplerianPropagator.propagate(
                a, e, i, raan, 0, 0, dt, GM);
            long secs = (long) dt;
            int hh = (int)(secs / 3600), mm = (int)((secs % 3600) / 60);
            double ss = dt % 60;
            sb.append(String.format("2000-001T%02d:%02d:%09.6f  ", hh, mm, ss));
            sb.append(String.format("%.6f  %.6f  %.6f  %.9f  %.9f  %.9f%n",
                sv[0] / 1000, sv[1] / 1000, sv[2] / 1000,   // km
                sv[3] / 1000, sv[4] / 1000, sv[5] / 1000));  // km/s
        }
        return sb.toString();
    }

    // ══════════════════════════════════════════════════════════════════════
    // PUBLISHED ORBITAL ELEMENT TRUTH CASES  [Vallado2013]
    // Algorithm 9 (rv2coe) test — given r,v derive elements:
    // ══════════════════════════════════════════════════════════════════════

    /**
     * Vallado FADA 4th ed., Algorithm 9 (rv2coe) self-consistency test.
     * Starting from known elements → compute r,v → recover elements.
     * The round-trip must close to machine precision.
     * These element sets are independent of any propagator.
     */
    public static final List<double[]> RV2COE_ELEMENT_SETS = List.of(
        // {a [m], e, i [°], Ω [°], ω [°], ν [°]}
        new double[]{RE + 500_000, 0.001,  28.5,  45.0,  30.0,  60.0},   // LEO
        new double[]{RE + 400_000, 0.000,  51.6,  138.0,  0.0,   0.0},   // ISS-like circular
        new double[]{26_560_000,   0.720,  63.4,  270.0, 270.0,  0.0},   // Molniya
        new double[]{42_164_170,   0.001,   0.1,  90.0,   0.0,  90.0},   // near-GEO
        new double[]{RE + 600_000, 0.000,  97.79,  0.0,   0.0,  45.0},   // SSO polar
        new double[]{RE + 300_000, 0.050,  28.5,  200.0, 180.0, 135.0}   // eccentric LEO
    );

    /**
     * Round-trip tolerance: elements → rv → elements must recover original
     * within these limits.
     */
    public static final double RV2COE_A_TOL_M      =  1.0;    // 1 m SMA
    public static final double RV2COE_E_TOL        =  1e-10;  // eccentricity
    public static final double RV2COE_ANGLE_TOL_DEG = 1e-6;   // angular elements
}
